djangoDemo/djangoDemo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from app_demo import views


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^hello/$', views.hello), # use url to find the def in views
    path('hrs/',include('hrs.urls')) , # use include to get all the path in one time
    path('polls/',include('polls.urls')), #include('polls.urls')) is the path like //djangoDemo/polls/urls.py
    path('vote/',include('schoolvoting.urls'))
]

djangoDemo/hrs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index, name='index')
]

djangoDemo/schoolvoting/urls.py
from django.urls import path

from . import views

app_name ='schoolvoting'

# common views
urlpatterns = [
    path('',views.show_subjects, name="index"),
    path('<int:subject_no>/teachers/',views.teachers, name = "teachers"),
    path('praise/<int:teacher_no>', views.praise_or_criticize, name = 'praise'),
    path('criticize/<int:teacher_no>', views.praise_or_criticize, name='criticize'),
    path('login', views.login, name='login'),
    path('register', views.register,name='register')
]

djangoDemo/schoolvoting/models.py
from django.db import models

# Create your models here.

class Subject(models.Model):
    no = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=20)
    intro = models.CharField(max_length=511,default='',verbose_name='introduction')
    create_date=models.DateField(null=True)
    is_hot= models.BooleanField(default=False)
    def __str__(self):
        return self.name


class Teacher(models.Model):
    no=models.AutoField(primary_key=True)
    name=models.CharField(max_length=20)
    detail=models.CharField(max_length=1023,default='',blank=True)
    photo=models.CharField(max_length=1023,default='')
    good_count=models.IntegerField(default=0)
    bad_count=models.IntegerField(default=0)
    subject = models.ForeignKey(to=Subject,on_delete=models.PROTECT,db_column='sno')


class User(models.Model):
    no = models.AutoField(primary_key=True)
    username = models.CharField(max_length=20,unique=True)
    password = models.CharField(max_length=32)
    reg_date = models.DateTimeField(auto_now_add=True,verbose_name='register date')

djangoDemo/schoolvoting/views.py
from django.shortcuts import render,redirect

from .logical.register import RegisterForm
from .models import Subject, Teacher
from django.http import JsonResponse

# Create your views here.

def show_subjects(request):
    subjects = Subject.objects.all()
    return render(request, 'schoolvoting/subject.html',{'subjects':subjects})

def teachers(request,subject_no):
    try:

        subject = Subject.objects.get(no=subject_no)
        teachers = subject.teacher_set.all()
        return render(request,'schoolvoting/teachers.html',{
            'subject':subject,
            'teachers':teachers
        })
    except (KeyError,ValueError,Subject.DoesNotExist):
        return redirect('/')

def praise_or_criticize(request,teacher_no):
    try:
        tno=teacher_no
        teacher=Teacher.objects.get(no=tno)
        print(request.path)
        if 'praise' in request.path:
            teacher.good_count+=1
        else:
            teacher.bad_count+=1
        teacher.save()
        data = {'code':200, 'hint':'Operation Successful'}
    except (KeyError,ValueError,Teacher.DoesNotExist):
        data = {'code':404, 'hint':'Operation Failed'}
    return JsonResponse(data)

def register(request):
    page='schoolvoting/register.html'
    hint=""
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            page='schoolvoting/login.html'
            hint='Register successfully! Please Login!'
        else:
            hint = "Please enter valid information!"
    return render(request,page,{'hint':hint})

def login(request):
    return render(request,'schoolvoting/login.html')

djangoDemo/templates/schoolvoting/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <h1>Welcome to login page</h1>
</body>
</html>

djangoDemo/templates/schoolvoting/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    <h1>User Register</h1>
<hr>
<p class="hint">{{hint}}</p>

<form action="{%url 'schoolvoting:register'%}" method="post">
        {% csrf_token %}
    <div class="input">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username">
    </div>
    <div class="input">
        <label for="password">Password:</label>
        <input type="password" id="password" name="password">
    </div>
        <div class="input">
        <label for="repassword">Confirm Password:</label>
        <input type="text" id="repassword" name="repassword">
    </div>
    <div class="input">
        <input type="submit" value="Submit">
        <input type="reset" value="Reset">
    </div>
</form>
<a href="{% url 'schoolvoting:login' %}">Return Login</a>
</body>
</html>

djangoDemo/templates/schoolvoting/subject.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>All Subjects</title>
</head>
<body>
    <h1>All Subjects</h1>
    <hr>
{% for subject in subjects %}
    <div>
        <h3>
            <a href="{% url 'schoolvoting:teachers' subject.no%}">
                {{subject.name}}
            </a>
            {% if subject.is_hot %}
            <img src="{% static '/images/hot-icon-small.png'%}" width="32" alt="">
            {% endif %}

        </h3>
        <p>{{subject.intro}}</p>
    </div>
{% endfor %}
</body>
</html>

djangoDemo/templates/schoolvoting/teachers.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="{% static '/js/ajax.js' %} "></script>
    <title>Teacher</title>
</head>
<body>
    <h1>{{subject.name}} Teacher information</h1>
<hr>
{% if teachers%}
{% for teacher in teachers%}
<div>
    <div>
        <img src="{% static teacher.photo %}" alt="">
    </div>
    <div>
        <h3>{{teacher.name}}</h3>
        <p>{{teacher.detail}}</p>
        <p class="comment">
            <a href="{% url 'schoolvoting:praise' teacher.no%}">Good comments</a>(<span>{{teacher.good_count}}</span>)
            <a href="{% url 'schoolvoting:criticize' teacher.no%}">Bad comments</a>(<span>{{teacher.bad_count}}</span>)
        </p>
    </div>
</div>
{% endfor %}
{% else %}
<h3>There is no teachers under Subject {{subject.name}}</h3>
{% endif%}
<p>
    <a href="/vote">Main Page</a>
</p>



</body>
</html>